### ISSUE TITLE
what about Noisy Image 

### ISSUE THREAD

**Issue by WrathofBhuvan11** [Manyunze/DCSRN#2]
What if 3D input image say MHA files are noisy? say speckle or salt and pepper, etc etc

**Comment by YunzeMan** [comment]
What do you mean by "noisy"?

If both low and high res images have random pepper noise, then I believe the model cannot handle this situation, you might want to perform some smoothing methods before super-resolution.

If only low-resolution images have noise, the network can recover the high-res non-pepper ground truth.
